"""New baseline

Revision ID: 5c36db90269b
Revises: 93f1c336c80c
Create Date: 2024-10-23 21:49:22.198771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c36db90269b'
down_revision: Union[str, None] = '93f1c336c80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'assets', 'portfolios', ['portfolio_id'], ['id'])
    op.add_column('lessons', sa.Column('note', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_lesson', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'user_lesson', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_lesson', type_='foreignkey')
    op.drop_constraint(None, 'user_lesson', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_column('lessons', 'note')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    # ### end Alembic commands ###
