"""added lesson model

Revision ID: 7b251f228f5b
Revises: 241cf72c5b13
Create Date: 2024-10-21 22:37:05.211853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b251f228f5b'
down_revision: Union[str, None] = '241cf72c5b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'assets', 'portfolios', ['portfolio_id'], ['id'])
    op.add_column('lessons', sa.Column('taken', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_lesson', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_lesson', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_lesson', type_='foreignkey')
    op.drop_constraint(None, 'user_lesson', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_column('lessons', 'taken')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    # ### end Alembic commands ###
