"""added lesson model

Revision ID: 8761b36555b1
Revises: 7b251f228f5b
Create Date: 2024-10-22 14:23:29.286698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8761b36555b1'
down_revision: Union[str, None] = '7b251f228f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lesson',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'lesson_id')
    )
    op.create_foreign_key(None, 'assets', 'portfolios', ['portfolio_id'], ['id'])
    op.drop_column('lessons', 'taken')
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.add_column('lessons', sa.Column('taken', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_table('user_lesson')
    # ### end Alembic commands ###
