"""New baseline

Revision ID: 93f1c336c80c
Revises: 
Create Date: 2024-10-23 21:46:20.639310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f1c336c80c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'assets', 'portfolios', ['portfolio_id'], ['id'])
    op.add_column('lessons', sa.Column('first_question_first_choice', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('first_question_second_choice', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('first_question_third_choice', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('first_question_fourth_choice', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('first_correct_answer', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('second_question', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('second_question_first_choice', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('second_question_second_choice', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('second_question_third_choice', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('second_question_fourth_choice', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('second_correct_answer', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_lesson', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'user_lesson', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_lesson', type_='foreignkey')
    op.drop_constraint(None, 'user_lesson', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_column('lessons', 'second_correct_answer')
    op.drop_column('lessons', 'second_question_fourth_choice')
    op.drop_column('lessons', 'second_question_third_choice')
    op.drop_column('lessons', 'second_question_second_choice')
    op.drop_column('lessons', 'second_question_first_choice')
    op.drop_column('lessons', 'second_question')
    op.drop_column('lessons', 'first_correct_answer')
    op.drop_column('lessons', 'first_question_fourth_choice')
    op.drop_column('lessons', 'first_question_third_choice')
    op.drop_column('lessons', 'first_question_second_choice')
    op.drop_column('lessons', 'first_question_first_choice')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    # ### end Alembic commands ###
