"""added lesson model

Revision ID: 9a0095ee85aa
Revises: 899fcfae59bf
Create Date: 2024-10-21 22:04:46.754017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a0095ee85aa'
down_revision: Union[str, None] = '899fcfae59bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'assets', 'portfolios', ['portfolio_id'], ['id'])
    op.drop_column('lessons', 'taken')
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.add_column('user_lesson', sa.Column('taken', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'user_lesson', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'user_lesson', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_lesson', type_='foreignkey')
    op.drop_constraint(None, 'user_lesson', type_='foreignkey')
    op.drop_column('user_lesson', 'taken')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.add_column('lessons', sa.Column('taken', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    # ### end Alembic commands ###
